version: '3'
networks:
  network:
    driver: bridge
services:
  centos1:
    networks:
      - network
    hostname: centos1
    container_name: centos1
    healthcheck:
      test: [ "CMD-SHELL", "ps-aux" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always
    ports:
      - "9822:22"
      - "8098:8098"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "3g"
    memswap_limit: "5g"
    build:
      context: .
      dockerfile: ./centos1/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./centos1/common:/common
      - ./disk1:/sys/fs/cgroup
  centos2:
    networks:
      - network
    hostname: centos2
    container_name: centos2
    healthcheck:
      test: [ "CMD-SHELL", "ps-aux" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always
    ports:
      - "9922:22"
      - "8099:8098"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "3g"
    memswap_limit: "5g"
    build:
      context: .
      dockerfile: ./centos2/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./centos2/common:/common
      - ./disk2:/sys/fs/cgroup
  centos3:
      networks:
        - network
      hostname: centos3
      container_name: centos3
      healthcheck:
        test: [ "CMD-SHELL", "ps-aux" ]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 5s
      restart: always
      ports:
        - "10022:22"
        - "8100:8098"
      deploy:
        resources:
          limits:
            cpus: "1"
            memory: "3g"
      memswap_limit: "5g"
      build:
        context: .
        dockerfile: ./centos3/Dockerfile
      stdin_open: true
      tty: true
      volumes:
        - ./centos3/common:/common
        - ./disk3:/sys/fs/cgroup
